### PR TITLE
Update configuration for discount rust examples

### PR DESCRIPTION
**Pull request by dphm**
Part of https://github.com/Shopify/script-service/issues/5030

[Flatten input for discount functions](https://github.com/Shopify/shopify/pull/358360)

### CODE REVIEW

**Comment by dphm** [comment]
>We also have these examples here that are bundled with a full app. I think these should be definitive examples https://github.com/Shopify/scripts-apis-examples/tree/master/sample-apps/discount-functions-sample-app/extensions
>
>What do you think?

Ahhh okay I should update those as well, but I guess to remove these we should replace instructions in the tutorial to use the sample app instead of these?

**Comment by dphm** [comment]
Can we generate those in the sample app from these?

**Comment by dphm** [comment]
Idk if y'all would rather I add this separately but [conditions will be removed from shipping discounts](https://github.com/Shopify/shopify/pull/358671)

**Review by jianghong — APPROVED** [review]

**Comment by dphm** [comment]
I'm going to split this up a bit, first: https://github.com/Shopify/function-examples/pull/66

**Pull request closed without merging**
